#!/bin/bash

set -e -u

# Colors
RED='\033[1;31m'
NC='\033[0m'

exec 3>&1
exec 1>&2

source=$1

if [ -z "$source" ]; then
  echo "usage: $0 <path/to/source>"
  exit 1
fi

PATH=/usr/local/bin:$PATH

cd $source

payload=$(mktemp "/tmp/kubernetes-resource-request.XXXXXX")
cat > "$payload" <&0

AWS_ACCESS_KEY_ID=$(jq -r '.source.aws_access_key_id // ""' < "$payload")
export AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY=$(jq -r '.source.aws_secret_access_key // ""' < "$payload")
export AWS_SECRET_ACCESS_KEY
AWS_CLUSTER_NAME=$(jq -r '.source.aws_eks_cluster_name // ""' < "$payload")
export AWS_CLUSTER_NAME
AWS_DEFAULT_REGION=$(jq -r '.source.aws_default_region // ""' < "$payload")
export AWS_DEFAULT_REGION

aws eks update-kubeconfig --name=${AWS_CLUSTER_NAME}

CMD=$(jq '.params.kubectl' < "$payload")

if [ -z "$CMD" ]; then
     printf "\n ${RED} Error! The Kubectl CMD is not specified! Please, add the 'params.kubectl' property to your resource parameters. ${NC}\n"
     exit 1
fi

CMD="$(eval echo ${CMD})"

echo "kubectl ${CMD}"

kubectl ${CMD}
timestamp="$(jq -n "{version:{timestamp:\"$(date +%s)\"}}")"
echo "$timestamp" | jq -s add >&3
# vim: ai ts=2 sw=2 et sts=2 ft=sh
